### ISSUE TITLE
Make "Debug" output coloured

### ISSUE THREAD

**Issue by hamishwillee** [dronecore/DroneCore#103]
The output of the debug build with the fly_mission example is shown below. As you can see, the **Info** output is very clear (blue) but the **Debug** is white, and hence not so easy to differentiate from the app's output. 

I think we can assume that, since we aren't making our debug output available, users will almost always output white.

![image](https://user-images.githubusercontent.com/5368500/30892754-952f3be6-a37d-11e7-9746-9e09ffb9b5d8.png)

I am not sure what colour would be best/we have already used. But see the ubuntu green/blue above are pretty easy to discern!

**Comment by julianoes** [comment]
I like the green idea.
