### ISSUE TITLE
Add docs for public headers

### ISSUE THREAD

**Issue by julianoes** [dronecore/DroneCore#13]
The public headers need some doxygen (or other) comments.

**Comment by hamishwillee** [comment]
I'm going to suggest doxyen-style comments because because whether or not you use them it is pretty easy to write a parser to extract them. And if you don't want to write such a parser "straight away" you already have a toolchain in place that can give you docs.

**Comment by hamishwillee** [comment]
Also, haven't done proper research, but it looks like SWIG does support some Python autodoc features -http://www.swig.org/Doc2.0/SWIGDocumentation.html#Python_nn67
It may be that we can work "better" with this if we choose the right C++ docs syntax.
