### ISSUE TITLE
Add Gimbal telemetry

### ISSUE THREAD

**Issue by hamishwillee** [dronecore/DroneCore#141]
As per https://github.com/dronecore/DroneCore/pull/124#issuecomment-339501931 , add an API to get MOUNT_ORIENTATION information. This should probably be a `Telemetry` API.

**Comment by julianoes** [comment]
We actually have that in telemetry:
https://github.com/dronecore/DroneCore/blob/b811348d30ae82e605f9c2814c6f09208fe5cce7/plugins/telemetry/telemetry.h#L364-L376.
