### ISSUE TITLE
Asynchronus usage of `CallEveryHandler` 

### ISSUE THREAD

**Issue by shakthi-prashanth-m** [dronecore/DroneCore#149]
Can I use `CallEveryHandler` asynchronously ?
As per unit test [call_every_handler_test.cpp](https://github.com/dronecore/DroneCore/blob/develop/core/call_every_handler_test.cpp), `ceh.run_once()` should be called periodically for my handler to be called. Am I right ?
Kindly correct or suggest me.

Thanks,
Shakthi

**Comment by shakthi-prashanth-m** [comment]
Oh.. I see that `run_once()` is called [here](https://github.com/dronecore/DroneCore/blob/develop/core/device_impl.cpp#L243) ?

**Comment by julianoes** [comment]
Yes, calling it should be taken care of by `device_impl.cpp`.

**Comment by shakthi-prashanth-m** [comment]
Thanks @julianoes
