### ISSUE TITLE
FollowMe API feels inconsistent

### ISSUE THREAD

**Issue by hamishwillee** [dronecore/DroneCore#191]
* `bool set_config (const Config &config)` - I would expect this to return a `Result` type
* `void get_last_location(TargetLocation &last_location)` could reasonably be be `TargetLocation& get_last_location()`
* If we are checking ack, then `void  set_curr_target_location(const TargetLocation &location)` should return a `Result`.
* `set_curr_target_location()` should be `set_current_target_location()` or even better `set_target_location()`
* There should usually be matching async APIs.

**Comment by shakthi-prashanth-m** [comment]
@hamishwillee Thanks for reporting this. I will make changes accordingly.

**Comment by julianoes** [comment]
> There should usually be matching async APIs.

I have no strong opinion on this one. We can add async/sync APIs as required.

**Comment by hamishwillee** [comment]
>> There should usually be matching async APIs.

> I have no strong opinion on this one. We can add async/sync APIs as required.

Fine by me. This was just a dump of all the things that seemed odd :-)

**Comment by hamishwillee** [comment]
This will be fixed by https://github.com/dronecore/DroneCore/pull/199

**Comment by shakthi-prashanth-m** [comment]
@hamishwillee shall we close this ?
I believe Follow Me example is not part of this issue. Isn't it ?

**Comment by hamishwillee** [comment]
Yes, fixed :-)
