### ISSUE TITLE
Exposing Flight mode APIs in core/device_impl.h

### ISSUE THREAD

**Issue by shakthi-prashanth-m** [dronecore/DroneCore#193]
We have [methods](https://github.com/dronecore/DroneCore/blob/develop/core/device_impl.h#L86-L89) in `DeviceImpl` for PX4 param get/set; but we don't have methods to know/change flight mode in `DeviceImpl`. These methods are useful for plugins. 

Below are the plugins each of which maps to a **PX4 flight mode**:
- [Offboard plugin](https://github.com/dronecore/DroneCore/blob/develop/plugins/offboard/offboard_impl.cpp#L48)
- [FollowMe plugin](https://github.com/dronecore/DroneCore/blob/develop/core/device_impl.h#L86-L89)
- [Mission plugin](https://github.com/dronecore/DroneCore/blob/develop/plugins/mission/mission_impl.cpp#L682)

As of now (in above plugins), we're doing the hard way by using  `MAV_CMD_DO_SET_MODE`. I think it makes sense to expose a method for the same as part of `DeviceImpl` interface. 

At present we've a [public API to get flight mode](https://github.com/dronecore/DroneCore/blob/develop/plugins/telemetry/telemetry.h#L392) is part of `Telemetry `plugin. If other plugins want to know flight mode, they can't call `Telemetry` plugin API (which creates plugin dependency). So it is suitable and intuitive to move some of the useful flight mode APIs from `Telemetry` plugin to `Device` as well.

**Comment by hamishwillee** [comment]
Having this in the `DeviceImpl` for plugins makes sense to me. I would keep the public API in telemetry -
 that is where I would expect to look for it as an API user.keeping the "public" API in Telemetry

**Comment by julianoes** [comment]
I agree that this would be handy.

**Comment by hamishwillee** [comment]
So the answer is Yes. Feel free to close  - and add the functionality/or change this to an issue and keep open.

**Comment by julianoes** [comment]
The answer is yes but I won't get to it just yet.

**Comment by shakthi-prashanth-m** [comment]
#206 addressed it.
