### ISSUE TITLE
Maintaining Plugin list

### ISSUE THREAD

**Issue by shakthi-prashanth-m** [dronecore/DroneCore#229]
Its very useful to keep track of existing plugins may be in an xml. It can be used by gRPC too to load them.
Currently[ plugins.conf](https://github.com/dronecore/DroneCore/blob/develop/grpc/proto/plugins.conf) only holds name of the plugin. I think its more meaningful if it has brief description of each of them as below:

```
<plugin name="action" filename="libaction.so">
    <desc> Enables enables simple actions for a drone such as arming, taking off, and landing. </desc>
</plugin>
<plugin name="mission" filename="libmission.so">
    <desc> Enables waypoint missions with upload, download, etc capabilities </desc>
</plugin>
<plugin name="follow_me" filename="libfollow_me.so">
    <desc> Enables vehicle tracking of a specified target (typically a ground station carried by a user) </desc>
</plugin>
...
```
This list also serves as a technical advertisement of all supported features at once!

**Comment by JonasVautherin** [comment]
I believe that the [DroneCore-Proto](https://github.com/dronecore/dronecore-proto) repo is now doing that, and I don't feel like we need to keep this as an open issue.
