### ISSUE TITLE
Missing sample plan for example

### ISSUE THREAD

**Issue by hamishwillee** [dronecore/DroneCore#272]
https://github.com/dronecore/DroneCore/tree/develop/example/fly_qgc_mission

Does not contain "qgroundcontrol_sample.plan" as described in example: "(b) Use a pre-created sample mission plan in "example/fly_qgc_mission/qgroundcontrol_sample.plan"."

It would be good if this could be added :-)

**Comment by hamishwillee** [comment]
Actually, I see you have a plan here: https://github.com/dronecore/DroneCore/blob/develop/plugins/mission/qgroundcontrol_sample.plan

So perhaps just update the documentation in the example?

**Comment by shakthi-prashanth-m** [comment]
Yes! It was moved later. I'll update the example. Thanks!

**Comment by shakthi-prashanth-m** [comment]
@hamishwillee, Do you think this link is useful ? If not, I shall remove it.

**Comment by hamishwillee** [comment]
> @hamishwillee, Do you think this link is useful ? If not, I shall remove it.

Yes, I think removing it is a good idea.
