### ISSUE TITLE
How do I capture images being in offboard mode

### ISSUE THREAD

**Issue by shakthi-prashanth-m** [dronecore/DroneCore#278]
AFAIK, we can capture images during Mission mode. But if I want to capture images or stream video during offboard mode how do we do that ?  Is it something to be done by a plugin?

**Comment by hamishwillee** [comment]
Not supported yet. If it was, then I'd expect it to be done by a new Camera plugin (e.g. in conjunction with the Gimbal plugin). Note, I am assuming that camera messages are handled in offboard/all modes. I think they may be in PX4 but have not checked.

**Comment by julianoes** [comment]
Covered by #154.
