### ISSUE TITLE
[marketing] Branding and Design (mvp logo and color palette)

### ISSUE THREAD

**Issue by mrpollo** [dronecore/DroneCore#28]

**Comment by hamishwillee** [comment]
First version done.
![DroneCore](https://raw.githubusercontent.com/dronecore/docs/master/assets/site/dronecore_logo_full.png)

@mrpollo - should this be upper case for the "D" and "C" letters? If we are happy, then this item can be closed.

**Comment by mrpollo** [comment]
![dc](https://user-images.githubusercontent.com/317648/30622013-9ef81a00-9d63-11e7-8fed-374db890fa76.png)
