### ISSUE TITLE
[core] Python binding with swig

### ISSUE THREAD

**Issue by mrpollo** [dronecore/DroneCore#31]
- [ ] `device_uuids()` should return an array not an object `<Swig Object of type 'std::vector< uint64_t > *' at 0x104bbc090>`
- [ ] notify callback wrappers should convert from function to `dronecore::DroneCore::event_callback_t`
- [ ] enums shouldn't be flattened eg: `DroneCore::ConnectionResult::SUCCESS` `DroneCore.ConnectionResult_SUCCESS`
- [ ] test Action and Telemetry classes

**Comment by hamishwillee** [comment]
Closing - AFAIK we are no longer proceeding with SWIG
