### ISSUE TITLE
Choosing reference over pointer

### ISSUE THREAD

**Issue by shakthi-prashanth-m** [dronecore/DroneCore#314]
It is recommended to use references when we can, and pointers when we have to.
(Reference: https://isocpp.org/wiki/faq/references#refs-vs-ptrs)

We can replace `Device *_parent` to `Device & _parent` as I see that, its possible. We initialize while activating plugin and never modify it. Also, we have a method (below) that actually gives, **a reference to a device**, not pointer. 
```cpp
Device &device(uint64_t uuid);
```

Consider, below piece of application code:
```cpp
Device &device = dc.device(); // we get reference to device
auto action = std::make_shared<Action>(&device); // why pass its address ?

// Why not pass it as-is?
auto action = std::make_shared<Action>(device);
```
I just noticed this.
@julianoes, was it done intentionally for some vital reason? If not, then we can find similar usages and replace them properly.

**Comment by julianoes** [comment]
I tend to agree. Thanks for writing that up @shakthi-prashanth-m. Do you agree @JonasVautherin?
