### ISSUE TITLE
Support for `COMMAND_INT`

### ISSUE THREAD

**Issue by julianoes** [dronecore/DroneCore#326]
The `Device` class and `MavlinkCommands` class should support commands that use int32 for fields like latitude and longitude. This is e.g. required for ROI commands.

A starting point is here:
https://github.com/dronecore/DroneCore/blob/develop/core/mavlink_commands.h#L33-L35

**Comment by shakthi-prashanth-m** [comment]
@julian we should also consider the ones that have few parameters than that of Command INT like this https://mavlink.io/en/messages/common.html#MAV_CMD_SET_CAMERA_MODE ?

**Comment by julianoes** [comment]
@shakthi-prashanth-m no these fields are just omitted in the docs.

**Comment by shakthi-prashanth-m** [comment]
Addreseed in #351 .
