### ISSUE TITLE
Create a Dronecode SDK logo

### ISSUE THREAD

**Issue by hamishwillee** [dronecore/DroneCore#344]

**Comment by hamishwillee** [comment]
FYI, @mrpollo says this should be generated next week.

**Comment by julianoes** [comment]
What's the status here?

**Comment by hamishwillee** [comment]
@mrpollo We're watching you. Any progress on the logo? :-)

**Comment by mrpollo** [comment]
Let's use this logo for now
![](https://files.slack.com/files-pri/T0V5F863B-FAGPVNKME/image_uploaded_from_ios.jpg)

A shorter version can be the dronecode wings for now
![sdk-short](https://user-images.githubusercontent.com/317648/42230901-f1feb002-7e9e-11e8-903a-ea428b3061a7.png)

**Comment by hamishwillee** [comment]
Thanks @mrpollo - I have updated with the new logo. 

I don't use the short version anywhere, but for favicon I kept the old logo `</>` - I think that works well.
