### ISSUE TITLE
Example folder structure should be future proofed.

### ISSUE THREAD

**Issue by hamishwillee** [dronecore/DroneCore#36]
At the moment we have one [example](https://github.com/dronecore/DroneCore/tree/master/example) in the example folder. We're going to have more in future, so propose a dir structure like
**/example/takeoff_and_land/** or **/examples/takeoff_and_land/**

IF the wrapper APIs are to be included in the same repo then we should further sort by programming language: **/examples/takeoff_and_land/cpp/** or  **/examples/cpp/takeoff_and_land/**

**Comment by julianoes** [comment]
See #18

**Comment by hamishwillee** [comment]
Thanks. Works for me.
