### ISSUE TITLE
Dockerfile on dronecore/dronecore is out of date

### ISSUE THREAD

**Issue by hamishwillee** [dronecore/DroneCore#54]
This does not have doxygen - it is about a week old.

Would also be good to have a link back to the repo in https://hub.docker.com/r/dronecore/dronecore/

**Comment by julianoes** [comment]
I just checked this and found that doxygen is included and that I have pushed it:

```
docker push dronecore/dronecore
The push refers to a repository [docker.io/dronecore/dronecore]
43dc7cb93aa8: Layer already exists
29006b6830e2: Layer already exists
56827159aa8b: Layer already exists
440e02c3dcde: Layer already exists
29660d0e5bb2: Layer already exists
85782553e37a: Layer already exists
745f5be9952c: Layer already exists
latest: digest: sha256:a8352de2ade873eda8f94840e3c2e90b500d0b07f7a20c40c3a695808b9c9d19 size: 1777
```

I already pushed the updated one with doxygen when the comments were still a pull request. This is what might have confused you.

**Comment by julianoes** [comment]
Backlinks created, closing.

**Comment by hamishwillee** [comment]
Thank you. Don't know what happened, but looks great now.
