### ISSUE TITLE
DroneCore::ConnectionResult enum inconsistent name

### ISSUE THREAD

**Issue by hamishwillee** [dronecore/DroneCore#60]
The rest of the classes all just use "Result" for the enum name. I think we should be consistent.

This would also allow us to consistently name the method for getting the human readable string (e.g. `result_str`

It MAY also be worth deciding on a more descriptive name than just "Result". E.g. CommandResult, MessageResult, SendResult, APIResult etc.

**Comment by julianoes** [comment]
I agree that all the plugins should be consistent as they are. However, the Results that we get in `DroneCore::` are (right now) only concerned with connections and not general `DroneCore::` actions. There might be more functionality later in `DroneCore::` that could require other enums.

**Comment by hamishwillee** [comment]
Fair enough
