### ISSUE TITLE
Plugins should not try resending on disconnected devices

### ISSUE THREAD

**Issue by hamishwillee** [dronecore/DroneCore#67]
For example, if you disconnect the device but then try landing, the plugin will still try to send the message, and to resend it. 
```A
Altitude: 2.679 m
Disconnected device with UUID: 4294967298
Landing...
sending again, retries to do: 3  (21).
sending again, retries to do: 2  (21).
sending again, retries to do: 1  (21).
Retrying failed (21)
Land failed:Timeout
```
I am not sure what the correct behaviour should be, but certainly it is not a resend. Ideally the user should be notified of this when they try to make the method call - typically there is a device disconnected "Results".

**Comment by julianoes** [comment]
Fixed by #185.
