### ISSUE TITLE
gRPC: APIs expose through gRPC

### ISSUE THREAD

**Issue by avinash-palleti** [dronecore/DroneCore#95]
Currently there are only 5 APIs (ARM, TAKE_OFF, LAND, SEND_MISSION, FLY_MISSION) that are exposed. 
Apparently all the APIs that Dronecore expose, should be exposed through gRPC also.

**Comment by hamishwillee** [comment]
I don't know what those are, but they look like commands, not APIs. You need to expose objects for the entire public C++ API - as documented here: https://docs.dronecore.io/en/api_reference/

**Comment by avinash-palleti** [comment]
@hamishwillee through gRPC we will be exposing all the public APIs that these objects support.

**Comment by julianoes** [comment]
@JonasVautherin is following up on this in other issues, closing.
